# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # The "build" job
  building-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: homervt/demo-github-actions:latest
          cache-from: type=registry,ref=homervt/demo-github-actions:latest
          cache-to: type=inline
